apiVersion: apps/v1
kind: Deployment
metadata:
  name: zad2-deployment
  namespace: zad2-ns
  labels:
    app: zad2-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zad2-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavaialable: 2
      maxSurge: 5
  template:
    metadata:
      labels:
        app: zad2-server
    spec:
      containers:
      - name: zad2-server
        image: scoutertf2/zad2:c7cc3e9ecb5bcb35e315a70e5e4748aabf81322d
      dnsPolicy: ClusterFirst
      restartPolicy: Always
